name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: チェックアウト
        uses: actions/checkout@v4

      - name: Node.js をセットアップ
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: 依存関係をインストール
        run: npm ci

      - name: Astro をビルド
        run: npm run build
        env:
          BASE_URL: "/my-learning-site"

      - name: GitHub Pages 用のアーティファクトをアップロード
        uses: actions/upload-pages-artifact@v2
        with:
          path: "dist"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: GitHub Pages へデプロイ
        uses: actions/deploy-pages@v2
